services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dashboard
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --bind_ip_all

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DB_URL=mongodb://mongodb:27017/dashboard
      - DB_NAME=dashboard
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  trivy:
    image: aquasec/trivy:latest
    entrypoint: ["trivy"]
    command: ["image", "--severity", "HIGH,CRITICAL", "backend:latest"]
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 