services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dashboard
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: mongod --bind_ip_all

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DB_URL=mongodb://mongodb:27017/dashboard
      - DB_NAME=dashboard
      - SENDGRID_ID=your_sendgrid_id
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - SENDGRID_FROM_EMAIL=your_verified_sender_email
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 